### ISSUE TITLE
Error on clearing build folder and other issues

### ISSUE THREAD

**Issue by andylokandy** [elba/elba#17]
Elba constantly complains that it can't clear the build folder:
```
[2/3] Building targets...
     [error] Couldn't clear build directory K:\Code\Idris\recursion_schemes\target\build: access denied。 (os error 5)
```

---

Other todos:
- Allow more defaults in manifest (due to convention over configuration):
  - targets.lib.path -> `./src`
  - targets.test.name -> `project_name-main_name`
  - add targets.bin.path, which defaults to `./src`, and then the field `main` becomes a subpath of it.
  - add targets.test.path, which defaults to `./tests`.

- Don't fetch index repeatedly during a short interval (5 mins?). (Did it has the same strategy with git resolution? Retrieving packages of git resolution seemed to be quite faster than index.)

- Coloring the summary display to distinguish between the name-version and resolution.

For example:
```
Retrieving git/specdris 0.1.0 (git+https://github.com/vmchale/specdris#master)
^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cyan              white                             grey
```

**Comment by dcao** [comment]
- The latest commit has added some defaults to aid in the goal of "convention over configuration."
- I think it still makes sense to fetch an index repeatedly even in short intervals, because you don't know if within that interval if the package index has updated.
