### ISSUE TITLE
Compatibility with ipkg?

### ISSUE THREAD

**Issue by Redrield** [elba/elba#25]
Should elba be made to be able to resolve dependencies given an ipkg simply for compatibilities sake?

**Comment by dcao** [comment]
This would be pretty helpful for moving old projects onto elba. The issues I can see with tackling this project are parsing ipkg files and dealing with package names: all names in elba are namespaced, whereas ipkgs don't have namespaced names. Should we just throw a default namespace onto ipkg packages (`legacy/` or something)?

**Comment by Redrield** [comment]
Something like that would make sense

**Comment by karroffel** [comment]
I think this might be useful in both directions. For example I am using the vscode extension which starts a REPL in IDE mode. I think it does respect `.ipkg` files, so if elba could generate a file like this it might ease adoption because existing tools can be used.

**Comment by andylokandy** [comment]
@karroffel IDE support is experimentally implemented by https://github.com/elba/idris-elba-interface

**Comment by karroffel** [comment]
@andylokandy oh very nice thanks, unfortunately because of #73 it is not that useful to me right now :sweat_smile: But that's a problem for another place. Thank you for the link!

**Comment by andylokandy** [comment]
This feature is added in https://github.com/elba/elba/commit/fd70ddefef19d32aa51e4b3f8d11cfa826909036 😄  . Now elba respects .ipkg file for remote dependencies and for cli commands excluding `elba package`. Package will have namespace `legacy` and version `0.0.0`.
