### ISSUE TITLE
Implement an index backend.

### ISSUE THREAD

**Issue by andylokandy** [elba/elba#27]
A backend is the foundation for building the website, also, with the backend, we can offer the complete indexing functionalities with cli before we setup the website.

The backend receives `publish` requests invoked by cli, then stores the tarballs of sources and updates the index.

The backend should:

- be fast
- be disk space efficient
- be disaster tolerant
- support CDN (and heavily rely on it)
- be easy to deploy (for custom index)

Taking these into account, I have an initial idea for the backend structure:

- docker
- rust
- cloudflare
- fastDFS

**Comment by dcao** [comment]
These sound like pretty reasonable goals & approaches for a potential index backend, though I think it would be appropriate to move this issue to the [website repo](https://github.com/elba/website).
