### ISSUE TITLE
Depending on contrib

### ISSUE THREAD

**Issue by clayrat** [elba/elba#29]
How would I add the stdlib's `contrib` with elba, without adding the manifest file to the contrib folder? I tried just adding `idris_opts = ["-p contrib"]` in the target manifest, but I get 
```
The following packages were specified but cannot be found:
-  contrib
```

**Comment by dcao** [comment]
When passing options, each option should be its own element in the list, so your idris_opts key should read instead as: `idris_opts = ["-p", "contrib"]`.
