### ISSUE TITLE
Index CLI support

### ISSUE THREAD

**Issue by andylokandy** [elba/elba#31]
Since the index backend is basically working, we need CLI support to test against it for development purpose. The requested commands are `login` and `publish`. I've made up an exapmple:

- `elba login andylokandy my_github_access_token_Wp5k0WFxmgnxNnQOzLGpTdP`

This command invokes a `GET` request to the backend to path `/api/v1/users/login`. Then if the backend responds `200 OK`, elba stores the user token somewhere in cache, globally,

- `elba publish`

This command firstly builds the package to check its correctness and then invokes a `PUT` request to path `/api/v1/packages/publish`. Further, elba can resolve a publish queue for workspace packages by their dependency order, and transforms their local `+dir` resolutions into index before publish.

The error reporting facility is not yet implemented. When it is, it's likely to be:

```json
400 Bad Request

{error:"Package group name `idris-dev` has been already taken."}
```

**Comment by dcao** [comment]
One design question I've faced while implementing this is with who's responsible for specifying index backends; should indices themselves have a field in their config to specify the backend, or should the user specify what backends they want to access, separate from the list of indices?

**Comment by andylokandy** [comment]
Having the backend info in index's index.toml could be a great approach.

**Comment by andylokandy** [comment]
@dcao Hi David, how is the progress now?

**Comment by dcao** [comment]
I've made a little bit of progress in getting logins working, but I've been pretty busy recently, so I haven't gotten as much done as I would've liked. This feature should land by the end of this week.

**Comment by andylokandy** [comment]
This week sounds good.

**Comment by dcao** [comment]
The latest commit implements publishing, yanking, and logging in.

One change which I've made is to follow cargo with regards to how logins work - the website should deal with logging into Github and providing a single token which gets used at the command-line. If you're ok with this & the other changes, feel free to close the issue.
