### ISSUE TITLE
Search cli support

### ISSUE THREAD

**Issue by andylokandy** [elba/elba#35]
Add `search` and `add` subcommands. Expected behavior: 

```
elba search lightyear core
lightyear/core     0.2.1   some description
lightyear/parser  0.2.0   some description
other/lightyear-helper  0.1.0   some description
```
```
elba add lightyear/core
Added lightyear/core  0.2
```

Backend api:
```
https://example.com/api/v1/packages/search?q=lightyear%20core

[{
  "group":"lightyear",
  "package":"core",
  "description":"...",
  "licence:"...",
  "authors":"..."
},
...
]
```

~~The latest version and proper version for add subcommand should be resolved from index by elba itself.~~

Latest version would be provided by backend.

**Comment by dcao** [comment]
I don't think we need to rely on an api endpoint for managing search, since we already have local package indices that we can search through. The search functionality would be more useful for a web interface, I suspect.

**Comment by andylokandy** [comment]
The backend performs full text search upon name, description and readme. The result from backend is more relevant and useful. Of course we can fall back to index if backend fails(but when it does, the download service is also unavailable). In my opinion, the search command should depend on backend api, and the add command can still stick with the index.

**Comment by andylokandy** [comment]
@jhmcstanton The `https://github.com/elba/index` is index, and the backend, which is under development in https://github.com/elba/website, is not online now. Ideally, we will setup a website in which users could search packages, and see ranking, categories and download profiles. But in this stage, I would like to provide the minimum search support via cli command so as to put `elba` online as soon as possible.

**Comment by jhmcstanton** [comment]
I see, I didn't open the website repository and missed some of those details, woops. In that case, since search appears to be implemented in `elba/website`, we can stand that up locally and test against it, correct?

**Comment by andylokandy** [comment]
@jhmcstanton The backend is basically finished now and the elba itself is the last missing piece. 

We indeed can host a backend instance locally for testing. Further, a testing server is already online on my domain only for development purpose.

**Comment by dcao** [comment]
I messed up in the commit message; I meant to close #42...
