### ISSUE TITLE
Add `Registry` direct resolution.

### ISSUE THREAD

**Issue by andylokandy** [elba/elba#37]
This resolution is intended to only be used in index entries in order to eliminate hardcoded tarball url in index files.

```rust
pub struct DirectRes {
    ...
    Registry { name: Name, version: Version }
}
```

Index entry:

```
// before
{"name":"foo/bar","version":"0.0.0","dependencies":[],"yanked":false,"location":"tar+http://backend.com/api/v1/packages/download/?group=foo&package=bar&version=0.0.0"}

// after
{"name":"foo/bar","version":"0.0.0","dependencies":[],"yanked":false,"location":"registry+foo/bar#0.0.0"}
```

Elba can resolve registry resolution by invoking `download` api to backend to get the tarball. In addition, elba can have multiple backends and fallback to the other backend if the package does not exist. This should be helpful for user who wants to setup a private index that refers packages of official index.

**Comment by dcao** [comment]
Is there a problem with leaving hard-coded tar URLs in the index? It seems like the only benefit we'd gain from making this change is just shortening the location in the index.

**Comment by andylokandy** [comment]
The benefit is that we can change our host more easily, also it is sort of related to the concern of custom registry. 

But I feel unclear about it now. I think we have to refine the registry structure completely if possible.

**Comment by dcao** [comment]
What changes do you think should we make to registries?

**Comment by andylokandy** [comment]
After skimming through the repo, I've an intial idea now and I'll try to explain it below.

## Goals

The first thing I considered is what goals we want to achieve in the new registry design. And then, I outlined three main use case:

- Official registry
The official registry provides central package storing, searching and download services. This registry can be hardcode as default registry in elba.

- Mirror registry
A mirror registry is used to boost up connection speed in some low internet condition area. A mirror registry usually refuses upload request or even searching and login request. Also, the mirror registry should keep sync with main registry automatically.

- Custom registry
A custom registry could be setup by personal studios or companies, for private package hosting or anything else. The main difference between custom registry and mirror registry is that custom registry would not(but also be able to) keep sync with official registry, which means, in usual, a custom registry only hosts packages that it is interested in.

## Design on Server-side
If we think more deeply in the three goals above, we can find out that they can be abstracted into same website backends with different configurations.

|  | Allow Upload | Search & Login & Frontend website | Sync from other registry when package is missing | Allow referencing package from Git or Tar resolution
| ------ | ------ | ------ | ------ | ------ |
| Official registry | ✔  | ✔ | ❌ | ❌ |
| Mirror registry | ❌ | ❓ | ✔ | ❌ |
| Custom registr | ✔  | ❓ | ❓ | ✔ |

## Design on Client-side
There are two new features I want to add to elba:

### Registry resolution
As I suggested before, a `DirectRes::Registry` resolution would be added. And this is the only dependency resolution acceptable by official registry. In addition, the precise semantics of `DirectRes::Registry` is 'I want to have a copy of this version of this package from whichever trusted registry backend'.

### Prioritized registry list
We will add a new configuration item to config.toml : `[[Registries]]` or `[[Registry]]`, which contains urls to multiple backends. Then Elba would try to retrieve a package from the first to the last registry in sequence(if timeout occurs), thus we should always place the mirror registry on the top.

## Mics about registry and index
For now, elba hardcodes the index url and from the index it gets information of registry backend. But I think this design is a mistake for some reasons:

- Registry backend is dynamic while index is static, which means a backend can handle emergency when a index can not.

- Registry configuration can be changed on the air, when index needs to be `git push`.

My new design is relatively simple, and immature:
The backend provides a meta url in which it declears it's version, index url and policy by json. This url is also the url we fills in the registry list. And for ergonomics, we can have this url the same as the homepage of registry frontend, for example `https://elba.io/`, behind `PUT` http method, so that the users will not need to remember a extra url like `https://elba.io/meta` or something like that.

**Comment by andylokandy** [comment]
Due to the development issue, I think it has to be postponed.

**Comment by dcao** [comment]
I'm going to be implementing this before the release of 0.3.0. For the most part I think your ideas are sound, but I was thinking of making a few tweaks here and there. My idea for the design would be the following:

  - Add a new `DirectRes` variant: `DirectRes::Registry { url: Url, api_version: u16 }` 
  - If an index specifies a backing registry, all packages are automatically retrieved from the registry (e.g. an index cannot simultaneously specify a backing registry and have packages retrieved from a git repo)
  - Add a new api endpoint: `/registry`, which provides information about the registry in question
    - This endpoint is equivalent to your `/meta` suggestion from above, except it should include other information, like mirrors to retrieve packages from, and it should not contain the index url.
    - Alternatively, we could add a `[[registry]]` field to `index.toml` to allow the index to specify different mirrors; I'm not sure which of these options would be better...

This design would not add a separate list of registries, since we don't want to have to concern elba users with trying to figure out package mirrors - this should be the job of the registry maintainer.

**Comment by andylokandy** [comment]
> Add a new DirectRes variant: DirectRes::Registry { url: Url, api_version: u16 }

I think the registry meta is the better place to provide the api version, and my current belief is we should only rejuect service when the api verion that backend can provide is lower than the cli requests (eg. some new features is required).

> If an index specifies a backing registry, all packages are automatically retrieved from the registry (e.g. an index cannot simultaneously specify a backing registry and have packages retrieved from a git repo)

No concerns here but is there any reason why having this restriction?

> Add a new api endpoint: /registry, which provides information about the registry in question

In fact, I want to withdraw my previous words about registry and index. I think the index is more reliable than backend anyway, thus keeping the index as the primary entrypoint, just like what we already have, is the better choice.

> Alternatively, we could add a [[registry]] field to index.toml to allow the index to specify different mirrors; I'm not sure which of these options would be better...

> since we don't want to have to concern elba users with trying to figure out package mirrors - this should be the job of the registry maintainer.

I'm a bit confused here; the mirror server is not cdn that we have been talking about, the cdn is indeed maintained the registry maintainer. The mirror server is a connection speed up service that provided by third party organization or individuals to serve their own groups or their regions.

**Comment by andylokandy** [comment]
Let me explain the more precise semantics that I am thinking of.

The index:
- should tell what packages it is hosting, all packages(but not their dependencies) listed in a index should be able to be retrieved without looking into other index.
- should provide a backend url if any of its packages has `DirectRes::Register` resolution. (may `DirectRes::Backend` be more clear?)

The backend:
- provide meta, excluding mirrors server url and the index url.
- download, search, and so forth.

The cli:
- maintain a list of indices; query package from the first one to that last one.
- when package is found, retrieve it without querying the indices below.
- but when error occured on retrieval, query the indices below, and make a warn.
- if a package has dependencies, retrieve the dependency following from step 1.

**Comment by dcao** [comment]
@andylokandy I've added `DirectRes::Registry` to the latest commit (I wanted to stick with "Registry" to avoid confusion with compiler backends). For the most part, the design follows the semantics you've specified above, with a few caveats:

  - Since the website hasn't implemented the `/meta` endpoint yet, I've left this Registry method unimplemented for now.
  - I haven't included querying indices in turn for a package in order to keep builds more reproducible and predictable. If we were to add this feature in, it would be impossible to tell what index a package originates from based on its manifest file, since the specific index that package resolves to depends on what packages are available in which indices which are specified in a user's elba configuration. So for now, users still need to explicitly specify if they want to use a package from a non-default index.

**Comment by andylokandy** [comment]
Seems all good to me. I just have a question that whether search command only search the default registry or not? In fact I have this question because I've implemented a very small search engine for the website, which provides search sevice for the cli command, and it drive me to think whether we can embedded it into elba, which allows elba to search across all indicies and also lifts the search speed to instant. The search engine works in memory, with only around 100 lines of code. elba can gather package info and populate the engine on startup of search command. From the vision of benchmark, the startup with 100 entries takes up about 0.1ms, which is not the fastest in the world but should be totally enough in our use case. The additional requirement to this is adding keywords into index. There is a tradeoff.

**Comment by dcao** [comment]
I think it'd make sense to move search to be completely client-side; would this involve using your new `simsearch` package then?

**Comment by andylokandy** [comment]
I'd think so unless you don't want to support fuzzy search.

**Comment by andylokandy** [comment]
I'll open a new issue for this.
