### ISSUE TITLE
Run tests via testpkg option / synthesize main for tests?

### ISSUE THREAD

**Issue by clayrat** [elba/elba#39]
It seems that elba requires tests to have a `Main.main` function, which makes using `elba test` incompatible with the built-in `--testpkg` option, that synthesizes such a function itself given a list of test suites.

**Comment by andylokandy** [comment]
I am not quite sure about the original design but AFAICS, elba now intends to replace the idrisipkg, which means elba may not be compatible with the original project structure. @dcao Is that correct?

**Comment by dcao** [comment]
@clayrat As of `0.2.0` this feature has already been implemented; internally, tests are implemented as specialized binary targets, and in elba manifest files, a binary target does not need to have a function `Main.main`; elba will already synthesize it if needed. There's some information in [the guide](https://elba.readthedocs.io/en/latest/usage/manifest.html#targets) about this (if this wasn't clear in the documentation, please let me know so I can fix it up), but the shortened version is this:

If the "main" function for your tests is in the file `tests/Tests.idr`, and the "main" function is called `specSuite`, the syntax for specifying that target would be as follows:

```toml
[[targets.test]]
path = "tests"
main = "Tests.specSuite"
```

**Comment by andylokandy** [comment]
I think what @clayrat said is a test list that will be used to generate a complete maon function with specific test suit.

**Comment by clayrat** [comment]
Oh, it's enough for me that it can synthesize a `main` for a given test suite, and doesn't need to have a `Main.main`. The guide speaks of `Main` and doesn't mention code sythesis, so I was under the impression that this is unsupported.
