### ISSUE TITLE
The Idris Rewrite

### ISSUE THREAD

**Issue by dcao** [elba/elba#40]
The original plan was to build up a robust Rust version of elba, wait for new packages to be created, and then piggyback off of those for an Idris rewrite. However, the second step isn't really happening, so I think we should just jump straight into rewriting elba in Idris now and deal with all the new packages that need to be made. By having elba be written in the language it's for, we can hopefully kickstart the package community and improve adoption (you don't need two separate language toolchains now).

The new version of elba should ideally accomplish the following (in order from most to least plausible/realistic/sensical?):

- **Match the Rust version feature-wise.** This goes without saying.

- **Be [Blodwen](https://github.com/edwinb/Blodwen) compatible**. Not only should elba be able to adapt to the changes made in Blodwen (`*.ttc` files which go in `build/` folders instead of `*.ibcs` strewn about in the same folder as their source file, etc.), but elba and any dependency that it needs should be able to be compiled with Blodwen. The elba rewrite should also probably support Idris 1.x in some capacity and transparently work with both versions.

- **Clean up remote support**. elba's support for remote indices/registries is still a bit lacking since we don't have a real index or registry to work with. Now that we have a [working website backend](https://github.com/elba/website), we can work to properly test remotes and their associated features (this includes fixing some potential bugs with the dependency solver). This should resolve #33, #35, and #37.

- **Work more robustly in certain situations.** This refers to nothing in particular, just the fact that the Idris rewrite should try to work more gracefully (or at least fail more gracefully) when things go wrong (e.g. files go missing, the build directory can't be acquired, etc.).

- **Switch to Dhall for all configuration files**. This is probably the most ambitious and least realistic idea: it would require writing a complete Dhall interpreter in Idris, something which exists for nothing except Haskell at the moment. However, because Dhall is so flexible, it opens the door to some advanced functionality and programmability; [cpkg](https://github.com/vmchale/cpkg) is the only precedent I can think of at the moment for using Dhall.

The plan is to develop the rewrite on its own branch in this repository and keep the Rust version as the master branch; once the Idris version stars nearing completion, which can fork the Rust version into its own branch and switch the Idris version to master. Throughout this process, there are gonna be new libraries added to the elba org for common things that can be used by the entire Idris ecosystem (path handling, semver handling, etc.). Ideally, elba would be finished around the time that an official release of "Idris 2" happens so that we can coincide nicely with that release.

**Comment by andylokandy** [comment]
I felt quite uneasy after reading your new plan. Bascially it's because I don't believe we can build the whole ecosystem in idris  for the pm. I started to realize these days that idris is indeed a research language and no one would expect to build product level applications in idris. If you look in to the idris channel in reddit and mail lists, you will find that they are always talking about the language features and proofs, and only the discussions about practical things (like git, tar and networking) are missing. All in all, I think it's impossible to self-host the pm in idris now.

**Comment by dcao** [comment]
Idris is a research language, yes, but Haskell is also technically still a "research language"; in any case, Idris was meant to be a language that could be used both for proofs and for general-purpose programming. The problem with waiting for other people to make libraries is that there is no real upper bound on when that could happen; the proper libraries could fall in place tomorrow or never, so I think it makes sense to at least attempt to implement elba in Idris now.

**Comment by andylokandy** [comment]
Haskell has made a good balance between research and engineering in the past 30 years. But even beening developed over 30 years, Haskell still has packages that can be listed in only one single web page, while Rust already has over 20k+ crates in 3 years.

Yes, we indeed need someone to kick off the community and focus on engineering. But this is far beyond our original goals on elba. I think I was hoping to give assistance to community by building a robust package manager, but not being the community itself, building all missing pieces in idris, and without a working pm.

I still think that we should stick with the rust version now until it's totally working online.

**Comment by dcao** [comment]
I think that's a reasonable plan to follow; I think we'll keep developing the Rust version and expanding its featureset then, but we'll also add some Idris libraries to the elba org which might be helpful for future development.

**Comment by dcao** [comment]
Since this seems like a pretty far-off concern for now, I'm gonna close this issue in favor of a more realistic roadmap
