### ISSUE TITLE
Run search command locally

### ISSUE THREAD

**Issue by andylokandy** [elba/elba#49]
More info in: https://github.com/elba/elba/issues/37

Implement a new search stategy to allow search command to run locally with support of index.

Details:
1. Elba gathers info from index, including package group/name, latest version and the keywords of the latest version.
2. Feed group/name and keywords to simsearch.
3. Seach and show the top results.

Checklist:

- [x] Publish simsearch to crates.io
- [ ] Add keywords field to index
- [x] Implement the new search command
- [ ] Upload keywords to index on publish (website)

**Comment by andylokandy** [comment]
[`simsearch`](https://crates.io/crates/simsearch) is published to crates.io.

**Comment by andylokandy** [comment]
I think we might not want to search on keyword. Because the cli is not the same as website where you can see what the keyword of each package is when you can't do it in cli.

**Comment by dcao** [comment]
I agree; plus it might be confusing for an end user trying to search for package and getting search results which don't correspond to the name of a package.
I'm going to consider this issue closed then.
