### ISSUE TITLE
Allow to define `include` in manifest

### ISSUE THREAD

**Issue by andylokandy** [elba/elba#56]
Read more: https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields-optional
Related to https://github.com/elba/elba/issues/54

**Comment by andrevidela** [comment]
@andylokandy do you have pointers as to how to implement that? I would like to give it a go.

**Comment by andylokandy** [comment]
@andrevidela Thanks for your help! This task is quite easy; all codes needed to modify is in `src/lib/package/manifest.rs`. First, an `include` field should be added to `PackageInfo` which holds the information parsed from manifest. Then in `Manifest::list_files()`, where we handle the exclude/include strategy, we take the `include` list into consideration. The inclusive list should have higher priority than the exclusive list.
