### ISSUE TITLE
Build release from source fails

### ISSUE THREAD

**Issue by steshaw** [elba/elba#59]
I tried building `elba` from source [according to the docs](https://elba.readthedocs.io/en/latest/usage/quick_start.html#building-elba) but I got an error:

```sh-session
$ cargo install --release
error: Found argument '--release' which wasn't expected, or isn't valid in this context

USAGE:
    cargo install [OPTIONS] [--] [crate]...

For more information try --help
```

I tried `cargo install --path=. --release` with the same error. I'm currently building without `--release`. Seems to be working 😄.

**Comment by andylokandy** [comment]
Thanks you for bring this up.

The command used to build from source should be `cargo install --path .` We'll fix the doc later.

**Comment by steshaw** [comment]
👍
