### ISSUE TITLE
`error: one or more packages couldn't be built`

### ISSUE THREAD

**Issue by marcosh** [elba/elba#70]
building my library I often get an error like

```
[error] Couldn't build library target for statebox/idris-ct 0.1.0 (dir+/home/marcosh/projects/statebox/idris-ct)
> "idris" "--check" "-p" "contrib" "Monad/VerifiedMonadAsMonad.lidr"


error: one or more packages couldn't be built
```

not necessarily on the same file every time.

Compiling directly with `idris` works fine.
Would it be possible to have a more verbose output explaining what the issue is?

**Comment by andylokandy** [comment]
Could you share a copy of your project?

**Comment by marcosh** [comment]
sure, you can find it here: https://github.com/statebox/idris-ct

thanks for the quick response

**Comment by andylokandy** [comment]
I've built it successfully. Could you provide your idris version and elba version? And make sure you're using elba 1.3.2.

**Comment by marcosh** [comment]
I'm using idris 1.3.2 and elba 0.3.1

sometimes it builds also for me, but sometimes it doesn't, and the failure does not always happen compiling the same file. That's why it would be nice to have a more verbose output to be able to understand what is going on

**Comment by andylokandy** [comment]
What I can tell from your error log is that idris exited with non-zero code and without any informative output, as there are two blank lines where the first one is stderr.

I've tried to reproduce the problem you have so that I can look into the details. To give some information, I am using idris 1.3.2 and elba 0.3.1 either on macos 10.14.6.

**Comment by marcosh** [comment]
so you think this could be an `idris` issue? Would there be a way to print out also `stdout`? And maybe providing a way to use `idris` with the `--V2` and `log LEVEL` options?

**Comment by andylokandy** [comment]
elba would print stdout as well if there are some. So it's a bit difficult to deal with it now.

**Comment by marcosh** [comment]
nice! thanks a lot for the help!
