### ISSUE TITLE
Missing README breaks package information page

### ISSUE THREAD

**Issue by marcesquerra** [elba/elba#72]
I've published a very small library in the public registry and, in the first version, I forgot to add a README file.

This causes the page that shows information about the library to show a weird error:

![lib-screenshot](https://user-images.githubusercontent.com/2683206/66722566-3ac9db80-ee07-11e9-8984-fae1541956d8.png)

Can be seen in here:
https://elba.pub/package/marcesquerra/idristest/0.1.0

Once I've added a README in the new version, the problem is gone:
https://elba.pub/package/marcesquerra/idristest/0.1.1

**Comment by andylokandy** [comment]
Thank you for the first package on elba.pub!! 😆 ane thank you for reporting this issue.

You might also want to add `desciption`, `keywords` and `repository` items in the manifest, as they all have corresponding UI elements on the web page!

**Comment by marcesquerra** [comment]
Thanks! I’ll do that with the next release I’m preparing :)

By the way, I see now that there is a different repo for the website. Should I have reported this there?

**Comment by andylokandy** [comment]
No, it's fine wherever to report the issue. XD

**Comment by andylokandy** [comment]
Solved in https://github.com/elba/website/commit/3b8cce066414d1d7074500a6a0bc6632acbe246d
