### ISSUE TITLE
Configuring flags passed to elba repl

### ISSUE THREAD

**Issue by kozross** [elba/elba#75]
I use [idris-mode][1] extensively, which requires a running REPL. I use ``idris repl`` for this, but unfortunately, I constantly have to remember to pass certain arguments to it (notably, ``-p contrib``). Is there a way I can set up my Elba configuration (either globally or per-project) to add these flags automatically?

[1]: https://github.com/idris-hackers/idris-vim

**Comment by andylokandy** [comment]
I think this is related to https://github.com/elba/elba/issues/73. But I am no available recently :-( , would you mind to help improve it?

**Comment by kozross** [comment]
I'm afraid I don't know Rust at all.

**Comment by andylokandy** [comment]
PTAL https://github.com/elba/elba/issues/73 😆
